name: Java CI with Gradle

on:
  push:
    branches: [ "main" ] # Updated branch name to "main"
  pull_request:
    branches: [ "main" ] # Updated branch name to "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Updated to v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2 # Updated to v2
        with:
          java-version: '11'
          distribution: 'adopt' # Updated to 'adopt'
      - name: Set executable permissions for gradlew
        run: chmod +x gradlew
      - name: Build and test with Gradle
        run: ./gradlew build test
      - name: Display test failures
        if: failure()
        run: cat build/test-results/test/*.xml
#LOLLL
